# Generated by Django 4.2 on 2023-12-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(null=True)),
                ('question', models.TextField(max_length=500, null=True)),
                ('opt1', models.CharField(max_length=80, null=True)),
                ('opt2', models.CharField(max_length=80, null=True)),
                ('opt3', models.CharField(max_length=80, null=True)),
                ('opt4', models.CharField(max_length=80, null=True)),
                ('correct_opt', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(null=True)),
                ('question', models.TextField(max_length=500, null=True)),
                ('opt1', models.CharField(max_length=80, null=True)),
                ('opt2', models.CharField(max_length=80, null=True)),
                ('opt3', models.CharField(max_length=80, null=True)),
                ('opt4', models.CharField(max_length=80, null=True)),
                ('correct_opt', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('feedback', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(null=True)),
                ('question', models.TextField(max_length=500, null=True)),
                ('opt1', models.CharField(max_length=80, null=True)),
                ('opt2', models.CharField(max_length=80, null=True)),
                ('opt3', models.CharField(max_length=80, null=True)),
                ('opt4', models.CharField(max_length=80, null=True)),
                ('correct_opt', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(null=True)),
                ('question', models.TextField(max_length=500, null=True)),
                ('opt1', models.CharField(max_length=80, null=True)),
                ('opt2', models.CharField(max_length=80, null=True)),
                ('opt3', models.CharField(max_length=80, null=True)),
                ('opt4', models.CharField(max_length=80, null=True)),
                ('correct_opt', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(null=True)),
                ('question', models.TextField(max_length=500, null=True)),
                ('opt1', models.CharField(max_length=80, null=True)),
                ('opt2', models.CharField(max_length=80, null=True)),
                ('opt3', models.CharField(max_length=80, null=True)),
                ('opt4', models.CharField(max_length=80, null=True)),
                ('correct_opt', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
