# Generated by Django 4.2 on 2023-12-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('attemp_count', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
    ]
