# Generated by Django 4.2 on 2023-12-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0002_userresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userresult',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
