# Generated by Django 4.2 on 2023-12-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0003_feedback_user_id_userresult_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsquestion',
            name='catagery',
            field=models.CharField(default='Awards', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currencyquestion',
            name='catagery',
            field=models.CharField(default='Currency', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthquestion',
            name='catagery',
            field=models.CharField(default='Health', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sportsquestion',
            name='catagery',
            field=models.CharField(default='Sports', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='techquestion',
            name='catagery',
            field=models.CharField(default='Technlogy', max_length=50, null=True),
        ),
    ]
