# Generated by Django 4.2.5 on 2023-12-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0004_awardsquestion_catagery_currencyquestion_catagery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresult',
            old_name='attemp_count',
            new_name='attend',
        ),
    ]
