# Generated by Django 4.2.5 on 2023-12-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0005_rename_attemp_count_userresult_attend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresult',
            name='attend',
        ),
    ]
