# Generated by Django 4.2.5 on 2023-12-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0006_remove_userresult_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsquestion',
            name='related_img',
            field=models.ImageField(null=True, upload_to='questions/related_images/difficult'),
        ),
        migrations.AddField(
            model_name='currencyquestion',
            name='related_img',
            field=models.ImageField(null=True, upload_to='questions/related_images/hard'),
        ),
        migrations.AddField(
            model_name='healthquestion',
            name='related_img',
            field=models.ImageField(null=True, upload_to='questions/related_images/intermide'),
        ),
        migrations.AddField(
            model_name='sportsquestion',
            name='related_img',
            field=models.ImageField(null=True, upload_to='questions/related_images/easy'),
        ),
        migrations.AddField(
            model_name='techquestion',
            name='related_img',
            field=models.ImageField(null=True, upload_to='questions/related_images/medium'),
        ),
    ]
