# Generated by Django 4.2 on 2024-01-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0008_currentaffairsquestion_historyquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaffairsquestion',
            name='catagery',
            field=models.CharField(default='Current_Affairs', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantsandanimalquestion',
            name='catagery',
            field=models.CharField(default='Plants_and_Animal', max_length=50, null=True),
        ),
    ]
